In [2]:
import torch

生成张量，并且改变形状

In [3]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape#shape 用来表示形状

torch.Size([12])

In [5]:
x.numel#numel 用来表示元素个数

<function Tensor.numel>

In [6]:
x.reshape(3,4)#reshape 用来表示形状的改变,但是不改变元素值

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

zeros和ones分别是生成全0和全1的张量

In [7]:
x=torch.zeros((2,3,4))
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
x=torch.ones((2,3,4))
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

张量之间的运算——两张量中对应元素进行运算

In [9]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

指数运算

In [10]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

cat将两个张量合在一起，dim=0说明尺寸为0,两张量堆叠起来;dim=1说明尺寸为1,两张量并排堆放

In [11]:
x=torch.arange(12,dtype=torch.float32).reshape(3,4)
y=torch.tensor([[2.0,1,4,3],[1,2,1,2],[4,3,2,1]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  1.,  2.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  1.,  2.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [ ]:
x==y #逻辑运算符构建二维张量

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [13]:
x.sum()

tensor(66.)

张量具有numpy数组一样的广播机制

In [14]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [15]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

取数和改变张量中对应位置的数

In [16]:
x,x[-1],x[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [17]:
x[1,2]=9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [18]:
x[0:2,:]=12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

python中会为新结果分配内存

In [19]:
before=id(y)
y=y+x
id(y)==before

False

原地执行

In [20]:
z=torch.zeros_like(y)
print(F"z={z},id(z)={id(z)}")
z[:]=y+x
print(F"z={z},id(z)={id(z)}")

z=tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),id(z)=139903917871328
z=tensor([[26., 25., 28., 27.],
        [25., 26., 25., 26.],
        [20., 21., 22., 23.]]),id(z)=139903917871328


In [21]:
before=id(x)
x+=y
id(x)==before

True

张量和numpy数组之间的转换

In [22]:
a=x.numpy()
b=torch.tensor(a)
type(a),type(b)

(numpy.ndarray, torch.Tensor)

In [23]:
a=torch.tensor(1.5)
a,a.item(),float(a),int(a)

(tensor(1.5000), 1.5, 1.5, 1)

直接赋值可能存在的问题

In [25]:
a=torch.arange(12)
b=a.reshape(3,4)
print(F"a={a}")
b[:]=2
a

a=tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])