# 线性代数知识点的应用

In [6]:
import torch
x=torch.tensor([2.0])
y=torch.tensor([3.0])
x+y,x-y,x*y,x/y,x**y

(tensor([5.]), tensor([-1.]), tensor([6.]), tensor([0.6667]), tensor([8.]))

In [7]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [8]:
x[3]

tensor(3)

In [9]:
len(x)

4

In [10]:
x.shape

torch.Size([4])

In [12]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [13]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [14]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [15]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()#使用clone()方法创建一个新的张量B，它与A具有相同的值和形状，但它们是不同的对象，具有不同的内存地址。这样对B的修改不会影响A。
A,B,A+B,id(A),id(B),id(A+B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 139825215430384,
 139825215429504,
 139830167159248)

In [18]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [19]:
A=torch.arange(24,dtype=torch.float32).reshape(2,3,4)
a=2
a+A,(a*A).shape,a*A

(tensor([[[ 2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9.],
          [10., 11., 12., 13.]],
 
         [[14., 15., 16., 17.],
          [18., 19., 20., 21.],
          [22., 23., 24., 25.]]]),
 torch.Size([2, 3, 4]),
 tensor([[[ 0.,  2.,  4.,  6.],
          [ 8., 10., 12., 14.],
          [16., 18., 20., 22.]],
 
         [[24., 26., 28., 30.],
          [32., 34., 36., 38.],
          [40., 42., 44., 46.]]]))

sum求和以及sum(axis=)按轴求和

In [21]:
A=torch.arange(20*2,dtype=torch.float32).reshape(2,5,4)
A,A.shape,A.sum()

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 torch.Size([2, 5, 4]),
 tensor(780.))

In [22]:
A_sum_axis0=A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]))

In [23]:
A_sum_axis1=A.sum(axis=1)
A_sum_axis1,A_sum_axis1.shape

(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]))

In [24]:
A_sum_axis2=A.sum(axis=2)
A_sum_axis2,A_sum_axis2.shape

(tensor([[  6.,  22.,  38.,  54.,  70.],
         [ 86., 102., 118., 134., 150.]]),
 torch.Size([2, 5]))

In [26]:
A_sum_axis0_1=A.sum(axis=(0,1))
A_sum_axis0_1,A_sum_axis0_1.shape

(tensor([180., 190., 200., 210.]), torch.Size([4]))

In [30]:
print(A.numel()),A

40


(None,
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]))

mean平均值

In [31]:
A.mean(),A.sum()/A.numel()

(tensor(19.5000), tensor(19.5000))

In [32]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

sum(keepdim=True)保留求和的维度，方便进行广播计算

In [33]:
Sum_A=A.sum(axis=1,keepdim=True)
Sum_A,Sum_A.shape

(tensor([[[ 40.,  45.,  50.,  55.]],
 
         [[140., 145., 150., 155.]]]),
 torch.Size([2, 1, 4]))

cumsum按轴累加

In [38]:
A.cumsum(axis=0),A

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 22., 24., 26.],
          [28., 30., 32., 34.],
          [36., 38., 40., 42.],
          [44., 46., 48., 50.],
          [52., 54., 56., 58.]]]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]))

dot点积

In [43]:
y=torch.ones(4,dtype=torch.float32)
x=torch.arange(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

mv矩阵向量积

In [46]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
A.shape,x.shape,torch.mv(A,x),A

(torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

mm矩阵乘法

In [45]:
B=torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

L2范数，是向量的长度，每一项平方求和开根号

In [47]:
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

L1范数，是每个元素的绝对值求和

In [48]:
torch.abs(u).sum()

tensor(7.)

矩阵frob范数，是矩阵元素的平方求和

In [50]:
torch.norm(B),torch.norm(torch.ones((4,9)))

(tensor(3.4641), tensor(6.))