# 自动求导

In [1]:
import torch
x=torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad_(True)
x.grad

In [3]:
y=torch.dot(x,x)*2
y

tensor(28., grad_fn=<MulBackward0>)

In [ ]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [ ]:
x.grad==4*x#上面y实际上是2*x^2,所以对x求导就是4*x

tensor([True, True, True, True])

In [10]:
#默认情况下，PyTorch会累加梯度到.grad属性中。为了避免混淆，我们需要在计算新的梯度前将现有的梯度清零。
x.grad.zero_()
y=sum(x)
y.backward()
x.grad

tensor([1., 1., 1., 1.], grad_fn=<ZeroBackward0>)

In [ ]:
x.grad.zero_()
y=x*x#这里实际上是一个矩阵，但是在深度学习中，我们需要计算的是批量重每个样本单独计算的偏导数之和，而不是微分矩阵
y.sum().backward()#所以这里对其进行求和在求导
x.grad

tensor([0., 2., 4., 6.], grad_fn=<ZeroBackward0>)

In [17]:
x.grad.zero_()
y=x*x
u=y.detach()#detach()将返回一个新的张量，这里使得u不再是x的函数，而是变成一个标量，其值为x*x，
z=u*x

z.sum().backward()
x.grad==u#所以这里的梯度是u,而不是2*x

tensor([True, True, True, True])

In [ ]:
x.grad.zero_()
y.sum().backward()#而这里y依然是一个向量
x.grad==2*x

tensor([True, True, True, True])