# 自定义层

In [2]:
import torch
from torch import nn
import torch.nn.functional as F

class CenteredLyaer(nn.Module):
    def __int__(self):
        super().__init__()
    def forward(self,X):
        return X -X.mean()

layer=CenteredLyaer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net =nn.Sequential(nn.Linear(8,128),CenteredLyaer())
Y=net(torch.rand(4,8))
Y.mean()

tensor(-3.2596e-09, grad_fn=<MeanBackward0>)

带参数的图层

In [4]:
class MyLinear(nn.Module):
    def __init__(self, in_units,units):
        super().__init__()
        self.weight=nn.Parameter(torch.randn(in_units,units))
        self.bias=nn.Parameter(torch.randn(units,))
    
    def forward(self,X):
        linear=torch.matmul(X,self.weight)+self.bias
        return F.relu(linear)

linear=MyLinear(5,3)
linear.weight

Parameter containing:
tensor([[ 0.3818,  1.0056,  0.2918],
        [-0.9862,  0.1691, -0.9979],
        [ 0.8592, -1.0538,  0.1152],
        [ 0.5046, -0.3942,  0.5318],
        [ 0.5362, -0.4282, -0.4495]], requires_grad=True)

In [5]:
linear(torch.rand(2,5))

tensor([[2.5686, 0.7676, 0.2952],
        [1.7141, 0.9880, 0.0000]], grad_fn=<ReluBackward0>)

In [6]:
net=nn.Sequential(MyLinear(64,128),MyLinear(128,4))
net(torch.rand(2,64))

tensor([[ 0.0000, 29.3431, 34.8944, 48.1719],
        [ 0.0000,  0.0000, 50.2394, 49.7295]], grad_fn=<ReluBackward0>)