存一个矩阵

In [1]:
import torch
from torch import nn
import torch.nn.functional as F

X=torch.arange(4)
torch.save(X,'X-file1')
x2=torch.load('X-file1')
x2


tensor([0, 1, 2, 3])

In [2]:
y=torch.zeros(4)
torch.save([X,y],'x-file2')
x2,y2=torch.load('x-file2')
(x2,y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [3]:
mydict={'x':1,'y':2}
torch.save(mydict,'x-file3')
mydict2=torch.load('x-file3')
mydict2

{'x': 1, 'y': 2}

In [7]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden=nn.Linear(20,128)
        self.out=nn.Linear(128,10)
    def forward(self,X):
        return self.out(F.relu(self.hidden(X)))

X=torch.randn(size=(2,20))
net=MLP()
y=net(X)

In [13]:
torch.save(net.state_dict(),'MLP.params')

In [14]:
clone=MLP()
clone.load_state_dict(torch.load('MLP.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=128, bias=True)
  (out): Linear(in_features=128, out_features=10, bias=True)
)

In [15]:
Y_clone=clone(X)
Y_clone==y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])