In [1]:
import torch
from torch import nn
torch.device('cpu'),torch.cuda.device('cuda'),torch.cuda.device('cuda:1')

(device(type='cpu'),
 <torch.cuda.device at 0x7f4199d9f250>)

In [2]:
torch.cuda.device_count()

1

In [3]:
def try_gpu(i=0):
    if torch.cuda.device_count()>=i+1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')
def try_all_gpu():
    devices=[torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())]
    return devices if devices else torch.device('cpu')


try_gpu(),try_gpu(10),try_all_gpu()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

In [4]:
x=torch.tensor([1,2,3])
x.device

device(type='cpu')

In [5]:
x=torch.ones(2,3,device=try_gpu())
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [6]:
z=x.cuda(0)
x+z

tensor([[2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')

In [7]:
z.cuda(0) is z

True

神经网络与gpu

In [8]:
net=nn.Sequential(nn.Linear(3,1))
net=net.to(device=try_gpu())
net(x)

tensor([[0.8039],
        [0.8039]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [9]:
net[0].weight.data.device

device(type='cuda', index=0)